apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: radwahatem/simple-python-app
        ports:
        - containerPort: 5000
